# -*- coding: utf-8 -*-
"""ReLu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-LMJtalgwaxAsRQRSwJ7m9R9u_-UZ1lG
"""

# X = entrada
# W = peso(weight)
# B = bias(sesgo)

#u = X1 x W1 + X2 x W2 + X3 x W3 + B ===> Y = f(u)

#Relu:
# Dara 0 si el valor x es menor a 0
# Dara x si el valor de x es mayor o igual a 0

X1 = int(input("ingrese primer atributo: "))
X2 = int(input("ingrese segundo atributo: "))

S1 = max(0,(X1 * 1)+(X2 * 1) + 0)
S2 = max(0,(X1 * 1)+(X2 * 1) + -1)
Y = max(0,(S1 * 1)+(S2 * -2) + 0)
print(f"valor calculado: {Y}")